
server:
  port: 9090

# 数据库连接配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    # type: org.apache.commons.dbcp2.BasicDataSource
    # dbcp2：
    #   max-wait-millis：10000
    #   min-idle：5
    #   initial-size：5
    #   validation-query：SELECT x
    #   connection-properties：
    #     characterEncoding: utf8

  # thymeleaf 配置
  thymeleaf:
    prefix: classpath:/templates/
    check-template-location: true
    suffix: .html
    encoding: UTF-8
    servlet:
      content-type: text/html
    mode: HTML5
    cache: false

# mybatis整合
mybatis:
#  config-location: classpath:mybatis.cfg.xml
  type-aliases-package: com.robin.blog.entity
  mapper-locations:
  - classpath:mappers/*.xml




